### ISSUE TITLE
Not removing past elements

### ISSUE THREAD

**Issue by robertervin** [manish0610/tileview-vs-repeat#1]
The following code produces a grid of products, but when more data is loaded, the old data is not removed from the DOM.

`<div class="content" vs-repeat vs-tile-view="true" vs-animation-enable="true" vs-autoresize="true">
    <div class="item" ng-repeat="product in products">`

While digging into the code, the `$scrollParent` and `$fillElement` aren't being instantiated in the directive's controller. This seems to happen due to the $digest cycle taking place while they are being set since it throws the `digest is already taking place` error when I tried to force a $digest. When I wrapped it in a $timeout, it correctly set it, but then there was only 1 row of elements, which upon further investigation was supported auto-resizing, which I thought was interesting.

**Comment by manishPatwari** [comment]
Call the safeApply() when you want to do force $digest().

There is a watch $scope.$watchCollection for identifying any changes in the data and it will update the DOM automatically.

If still you face any issue please send the code with your use-case.

**Comment by robertervin** [comment]
It turns out that wasn't an issue. It wasn't recycling the DOM elements because it wasn't detecting the scroll parent since the one my implementation is using is custom and a parent `div` of the `vs-repeat`. A simple jQuery selector fixed the issue and now it works like a charm.

**Comment by patwari-manish** [comment]
Great , I am closing the issue.
